version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dj45/dev:latest

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: dj45/prod:latest

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: dj45/test:latest
