version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dev:latest

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: prod:latest

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: test:latest
