version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: myapp-dev

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: myapp-prod

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: myapp-test
