name: Container Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t test1:latest .

    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag test1:latest ${{ secrets.DOCKER_USERNAME }}/test1:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/test1:latest

    - name: Install Veracode CLI
      run: |       
        pwd
        export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
        export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
        pwd
        curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      continue-on-error: true 
        

    # - name: Authenticate Veracode CLI
    #   run: |
    #     ./veracode configure --username ${{ secrets.VERACODE_API_ID }} --password ${{ secrets.VERACODE_API_KEY }}

    - name: Scan Docker Image with Veracode
      run: |   
        pwd
        # export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
        # export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_ID }}
        # export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
        # export DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
        ./veracode scan --source test1:latest --type image --format table
