name: Container Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t my-app .

    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Install Veracode CLI
      run: |
        curl -fsS https://tools.veracode.com/veracode-cli/install | sh
        # curl -LO https://downloads.veracode.com/securityscan/veracode-cli-latest-linux-x64.tar.gz
        # tar -xvzf veracode-cli-latest-linux-x64.tar.gz
        # sudo mv veracode-cli /usr/local/bin/veracode-cli
        

    - name: Authenticate Veracode CLI
      run: |
        veracode config --username ${{ secrets.VERACODE_API_ID }} --password ${{ secrets.VERACODE_API_KEY }}

    - name: Scan Docker Image with Veracode
      run: |
        veracode container-scan --image ${{ secrets.DOCKER_USERNAME }}/my-app:latest
